# Generated by Django 2.2.7 on 2019-11-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField()),
                ('post', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
