# Generated by Django 2.2.7 on 2019-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='random',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
