# Generated by Django 2.2.7 on 2019-11-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghosting', '0002_post_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='random',
        ),
    ]
