# Generated by Django 2.2.7 on 2019-11-22 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ghosting', '0003_remove_post_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 15, 31, 10, 580181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
